version: "3.5"
services:
  faves-for-api:
    container_name: faves-for-api
    build: .
    tty: true
    restart: always
    volumes:
      - .:/app
    depends_on:
      - faves-for-db
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DRIVER: "postgres"
      DATABASE_URL: "host=faves-for-db user=postgres dbname=postgres password=postgres sslmode=disable"
    command: sh ./build.sh
  faves-for-db:
    image: postgres:10-alpine
    container_name: faves-for-db
    ports:
      - 3306:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_HOST: localhost
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"
  
