// Code generated by entc, DO NOT EDIT.

package choiceanswer

import (
	"server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CratedAt applies equality check predicate on the "crated_at" field. It's identical to CratedAtEQ.
func CratedAt(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCratedAt), v))
	})
}

// CratedAtEQ applies the EQ predicate on the "crated_at" field.
func CratedAtEQ(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCratedAt), v))
	})
}

// CratedAtNEQ applies the NEQ predicate on the "crated_at" field.
func CratedAtNEQ(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCratedAt), v))
	})
}

// CratedAtIn applies the In predicate on the "crated_at" field.
func CratedAtIn(vs ...time.Time) predicate.ChoiceAnswer {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCratedAt), v...))
	})
}

// CratedAtNotIn applies the NotIn predicate on the "crated_at" field.
func CratedAtNotIn(vs ...time.Time) predicate.ChoiceAnswer {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCratedAt), v...))
	})
}

// CratedAtGT applies the GT predicate on the "crated_at" field.
func CratedAtGT(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCratedAt), v))
	})
}

// CratedAtGTE applies the GTE predicate on the "crated_at" field.
func CratedAtGTE(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCratedAt), v))
	})
}

// CratedAtLT applies the LT predicate on the "crated_at" field.
func CratedAtLT(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCratedAt), v))
	})
}

// CratedAtLTE applies the LTE predicate on the "crated_at" field.
func CratedAtLTE(v time.Time) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCratedAt), v))
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ParentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.Choice) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ParentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChoiceAnswer) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChoiceAnswer) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChoiceAnswer) predicate.ChoiceAnswer {
	return predicate.ChoiceAnswer(func(s *sql.Selector) {
		p(s.Not())
	})
}
