// Code generated by entc, DO NOT EDIT.

package answer

import (
	"time"
)

const (
	// Label holds the string label denoting the answer type in the database.
	Label = "answer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAnswerType holds the string denoting the answer_type field in the database.
	FieldAnswerType = "answer_type"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCratedAt holds the string denoting the crated_at field in the database.
	FieldCratedAt = "crated_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// Table holds the table name of the answer in the database.
	Table = "answers"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "answers"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_answers"
	// ParentTable is the table the holds the parent relation/edge.
	ParentTable = "answers"
	// ParentInverseTable is the table name for the Question entity.
	// It exists in this package in order to avoid circular dependency with the "question" package.
	ParentInverseTable = "questions"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "question_answers"
)

// Columns holds all SQL columns for answer fields.
var Columns = []string{
	FieldID,
	FieldAnswerType,
	FieldContent,
	FieldCratedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "answers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"question_answers",
	"user_answers",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultCratedAt holds the default value on creation for the "crated_at" field.
	DefaultCratedAt func() time.Time
)
