// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"server/ent/choiceanswer"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChoiceAnswerDelete is the builder for deleting a ChoiceAnswer entity.
type ChoiceAnswerDelete struct {
	config
	hooks    []Hook
	mutation *ChoiceAnswerMutation
}

// Where adds a new predicate to the ChoiceAnswerDelete builder.
func (cad *ChoiceAnswerDelete) Where(ps ...predicate.ChoiceAnswer) *ChoiceAnswerDelete {
	cad.mutation.predicates = append(cad.mutation.predicates, ps...)
	return cad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cad *ChoiceAnswerDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cad.hooks) == 0 {
		affected, err = cad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ChoiceAnswerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cad.mutation = mutation
			affected, err = cad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cad.hooks) - 1; i >= 0; i-- {
			mut = cad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cad *ChoiceAnswerDelete) ExecX(ctx context.Context) int {
	n, err := cad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cad *ChoiceAnswerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: choiceanswer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: choiceanswer.FieldID,
			},
		},
	}
	if ps := cad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cad.driver, _spec)
}

// ChoiceAnswerDeleteOne is the builder for deleting a single ChoiceAnswer entity.
type ChoiceAnswerDeleteOne struct {
	cad *ChoiceAnswerDelete
}

// Exec executes the deletion query.
func (cado *ChoiceAnswerDeleteOne) Exec(ctx context.Context) error {
	n, err := cado.cad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{choiceanswer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cado *ChoiceAnswerDeleteOne) ExecX(ctx context.Context) {
	cado.cad.ExecX(ctx)
}
