// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"faves4/ent/choice"
	"faves4/ent/choiceanswer"
	"faves4/ent/predicate"
	"faves4/ent/user"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChoiceAnswerQuery is the builder for querying ChoiceAnswer entities.
type ChoiceAnswerQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ChoiceAnswer
	// eager-loading edges.
	withOwner  *UserQuery
	withParent *ChoiceQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChoiceAnswerQuery builder.
func (caq *ChoiceAnswerQuery) Where(ps ...predicate.ChoiceAnswer) *ChoiceAnswerQuery {
	caq.predicates = append(caq.predicates, ps...)
	return caq
}

// Limit adds a limit step to the query.
func (caq *ChoiceAnswerQuery) Limit(limit int) *ChoiceAnswerQuery {
	caq.limit = &limit
	return caq
}

// Offset adds an offset step to the query.
func (caq *ChoiceAnswerQuery) Offset(offset int) *ChoiceAnswerQuery {
	caq.offset = &offset
	return caq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (caq *ChoiceAnswerQuery) Unique(unique bool) *ChoiceAnswerQuery {
	caq.unique = &unique
	return caq
}

// Order adds an order step to the query.
func (caq *ChoiceAnswerQuery) Order(o ...OrderFunc) *ChoiceAnswerQuery {
	caq.order = append(caq.order, o...)
	return caq
}

// QueryOwner chains the current query on the "owner" edge.
func (caq *ChoiceAnswerQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: caq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := caq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := caq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(choiceanswer.Table, choiceanswer.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, choiceanswer.OwnerTable, choiceanswer.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(caq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (caq *ChoiceAnswerQuery) QueryParent() *ChoiceQuery {
	query := &ChoiceQuery{config: caq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := caq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := caq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(choiceanswer.Table, choiceanswer.FieldID, selector),
			sqlgraph.To(choice.Table, choice.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, choiceanswer.ParentTable, choiceanswer.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(caq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChoiceAnswer entity from the query.
// Returns a *NotFoundError when no ChoiceAnswer was found.
func (caq *ChoiceAnswerQuery) First(ctx context.Context) (*ChoiceAnswer, error) {
	nodes, err := caq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{choiceanswer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) FirstX(ctx context.Context) *ChoiceAnswer {
	node, err := caq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChoiceAnswer ID from the query.
// Returns a *NotFoundError when no ChoiceAnswer ID was found.
func (caq *ChoiceAnswerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = caq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{choiceanswer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) FirstIDX(ctx context.Context) int {
	id, err := caq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChoiceAnswer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ChoiceAnswer entity is not found.
// Returns a *NotFoundError when no ChoiceAnswer entities are found.
func (caq *ChoiceAnswerQuery) Only(ctx context.Context) (*ChoiceAnswer, error) {
	nodes, err := caq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{choiceanswer.Label}
	default:
		return nil, &NotSingularError{choiceanswer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) OnlyX(ctx context.Context) *ChoiceAnswer {
	node, err := caq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChoiceAnswer ID in the query.
// Returns a *NotSingularError when exactly one ChoiceAnswer ID is not found.
// Returns a *NotFoundError when no entities are found.
func (caq *ChoiceAnswerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = caq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = &NotSingularError{choiceanswer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) OnlyIDX(ctx context.Context) int {
	id, err := caq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChoiceAnswers.
func (caq *ChoiceAnswerQuery) All(ctx context.Context) ([]*ChoiceAnswer, error) {
	if err := caq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return caq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) AllX(ctx context.Context) []*ChoiceAnswer {
	nodes, err := caq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChoiceAnswer IDs.
func (caq *ChoiceAnswerQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := caq.Select(choiceanswer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) IDsX(ctx context.Context) []int {
	ids, err := caq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (caq *ChoiceAnswerQuery) Count(ctx context.Context) (int, error) {
	if err := caq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return caq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) CountX(ctx context.Context) int {
	count, err := caq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (caq *ChoiceAnswerQuery) Exist(ctx context.Context) (bool, error) {
	if err := caq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return caq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (caq *ChoiceAnswerQuery) ExistX(ctx context.Context) bool {
	exist, err := caq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChoiceAnswerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (caq *ChoiceAnswerQuery) Clone() *ChoiceAnswerQuery {
	if caq == nil {
		return nil
	}
	return &ChoiceAnswerQuery{
		config:     caq.config,
		limit:      caq.limit,
		offset:     caq.offset,
		order:      append([]OrderFunc{}, caq.order...),
		predicates: append([]predicate.ChoiceAnswer{}, caq.predicates...),
		withOwner:  caq.withOwner.Clone(),
		withParent: caq.withParent.Clone(),
		// clone intermediate query.
		sql:  caq.sql.Clone(),
		path: caq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (caq *ChoiceAnswerQuery) WithOwner(opts ...func(*UserQuery)) *ChoiceAnswerQuery {
	query := &UserQuery{config: caq.config}
	for _, opt := range opts {
		opt(query)
	}
	caq.withOwner = query
	return caq
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (caq *ChoiceAnswerQuery) WithParent(opts ...func(*ChoiceQuery)) *ChoiceAnswerQuery {
	query := &ChoiceQuery{config: caq.config}
	for _, opt := range opts {
		opt(query)
	}
	caq.withParent = query
	return caq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CratedAt time.Time `json:"crated_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChoiceAnswer.Query().
//		GroupBy(choiceanswer.FieldCratedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (caq *ChoiceAnswerQuery) GroupBy(field string, fields ...string) *ChoiceAnswerGroupBy {
	group := &ChoiceAnswerGroupBy{config: caq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := caq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return caq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CratedAt time.Time `json:"crated_at,omitempty"`
//	}
//
//	client.ChoiceAnswer.Query().
//		Select(choiceanswer.FieldCratedAt).
//		Scan(ctx, &v)
//
func (caq *ChoiceAnswerQuery) Select(field string, fields ...string) *ChoiceAnswerSelect {
	caq.fields = append([]string{field}, fields...)
	return &ChoiceAnswerSelect{ChoiceAnswerQuery: caq}
}

func (caq *ChoiceAnswerQuery) prepareQuery(ctx context.Context) error {
	for _, f := range caq.fields {
		if !choiceanswer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if caq.path != nil {
		prev, err := caq.path(ctx)
		if err != nil {
			return err
		}
		caq.sql = prev
	}
	return nil
}

func (caq *ChoiceAnswerQuery) sqlAll(ctx context.Context) ([]*ChoiceAnswer, error) {
	var (
		nodes       = []*ChoiceAnswer{}
		withFKs     = caq.withFKs
		_spec       = caq.querySpec()
		loadedTypes = [2]bool{
			caq.withOwner != nil,
			caq.withParent != nil,
		}
	)
	if caq.withOwner != nil || caq.withParent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, choiceanswer.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ChoiceAnswer{config: caq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, caq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := caq.withOwner; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*ChoiceAnswer)
		for i := range nodes {
			if nodes[i].user_choiceanswers == nil {
				continue
			}
			fk := *nodes[i].user_choiceanswers
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_choiceanswers" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	if query := caq.withParent; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ChoiceAnswer)
		for i := range nodes {
			if nodes[i].choice_choiceanswers == nil {
				continue
			}
			fk := *nodes[i].choice_choiceanswers
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(choice.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "choice_choiceanswers" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Parent = n
			}
		}
	}

	return nodes, nil
}

func (caq *ChoiceAnswerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := caq.querySpec()
	return sqlgraph.CountNodes(ctx, caq.driver, _spec)
}

func (caq *ChoiceAnswerQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := caq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (caq *ChoiceAnswerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   choiceanswer.Table,
			Columns: choiceanswer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: choiceanswer.FieldID,
			},
		},
		From:   caq.sql,
		Unique: true,
	}
	if unique := caq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := caq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, choiceanswer.FieldID)
		for i := range fields {
			if fields[i] != choiceanswer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := caq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := caq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := caq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := caq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (caq *ChoiceAnswerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(caq.driver.Dialect())
	t1 := builder.Table(choiceanswer.Table)
	selector := builder.Select(t1.Columns(choiceanswer.Columns...)...).From(t1)
	if caq.sql != nil {
		selector = caq.sql
		selector.Select(selector.Columns(choiceanswer.Columns...)...)
	}
	for _, p := range caq.predicates {
		p(selector)
	}
	for _, p := range caq.order {
		p(selector)
	}
	if offset := caq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := caq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChoiceAnswerGroupBy is the group-by builder for ChoiceAnswer entities.
type ChoiceAnswerGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cagb *ChoiceAnswerGroupBy) Aggregate(fns ...AggregateFunc) *ChoiceAnswerGroupBy {
	cagb.fns = append(cagb.fns, fns...)
	return cagb
}

// Scan applies the group-by query and scans the result into the given value.
func (cagb *ChoiceAnswerGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cagb.path(ctx)
	if err != nil {
		return err
	}
	cagb.sql = query
	return cagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := cagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(cagb.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := cagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) StringsX(ctx context.Context) []string {
	v, err := cagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) StringX(ctx context.Context) string {
	v, err := cagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(cagb.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := cagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) IntsX(ctx context.Context) []int {
	v, err := cagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) IntX(ctx context.Context) int {
	v, err := cagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(cagb.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := cagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := cagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) Float64X(ctx context.Context) float64 {
	v, err := cagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(cagb.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := cagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := cagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cagb *ChoiceAnswerGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cagb *ChoiceAnswerGroupBy) BoolX(ctx context.Context) bool {
	v, err := cagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cagb *ChoiceAnswerGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cagb.fields {
		if !choiceanswer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cagb *ChoiceAnswerGroupBy) sqlQuery() *sql.Selector {
	selector := cagb.sql
	columns := make([]string, 0, len(cagb.fields)+len(cagb.fns))
	columns = append(columns, cagb.fields...)
	for _, fn := range cagb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(cagb.fields...)
}

// ChoiceAnswerSelect is the builder for selecting fields of ChoiceAnswer entities.
type ChoiceAnswerSelect struct {
	*ChoiceAnswerQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cas *ChoiceAnswerSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cas.prepareQuery(ctx); err != nil {
		return err
	}
	cas.sql = cas.ChoiceAnswerQuery.sqlQuery(ctx)
	return cas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cas.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) StringsX(ctx context.Context) []string {
	v, err := cas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) StringX(ctx context.Context) string {
	v, err := cas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cas.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) IntsX(ctx context.Context) []int {
	v, err := cas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) IntX(ctx context.Context) int {
	v, err := cas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cas.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) Float64X(ctx context.Context) float64 {
	v, err := cas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cas.fields) > 1 {
		return nil, errors.New("ent: ChoiceAnswerSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) BoolsX(ctx context.Context) []bool {
	v, err := cas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cas *ChoiceAnswerSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{choiceanswer.Label}
	default:
		err = fmt.Errorf("ent: ChoiceAnswerSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cas *ChoiceAnswerSelect) BoolX(ctx context.Context) bool {
	v, err := cas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cas *ChoiceAnswerSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cas.sqlQuery().Query()
	if err := cas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cas *ChoiceAnswerSelect) sqlQuery() sql.Querier {
	selector := cas.sql
	selector.Select(selector.Columns(cas.fields...)...)
	return selector
}
